export const AU_DATA = {
  basic: [
    {
      name: '真笑(自然)', nameEn: 'Genuine Smile',
      emoji: '😄',
      auCode: 'AU6+AU12',
      desc: '眼角收缩+嘴角上扬，影视级真实笑容',
      descEn: 'Cheek raiser + Lip corner puller, cinematic genuine smile',
      prompt: 'cinematic, genuine smile, AU6+AU12, photorealistic, Duchenne smile, eye crinkle',
      conflict: '',
    },
    {
      name: '假笑(职业)', nameEn: 'Social Smile',
      emoji: '🙂',
      auCode: 'AU12',
      desc: '仅嘴角上扬，无眼部动作',
      descEn: 'Lip corner puller only, no eye involvement',
      prompt: 'social smile, fake smile, AU12, professional, polite expression',
      conflict: '',
    },
    {
      name: '悲伤', nameEn: 'Sadness',
      emoji: '😢',
      auCode: 'AU1+AU4+AU15',
      desc: '眉头上提+皱眉+嘴角下拉',
      descEn: 'Inner brow raiser + Brow lowerer + Lip corner depressor',
      prompt: 'sad expression, AU1+AU4+AU15, teary eyes, downcast look',
      conflict: '',
    },
    {
      name: '愤怒', nameEn: 'Anger',
      emoji: '😠',
      auCode: 'AU4+AU5+AU23',
      desc: '皱眉+瞪眼+嘴唇紧绷',
      descEn: 'Brow lowerer + Upper lid raiser + Lip tightener',
      prompt: 'angry face, AU4+AU5+AU23, clenched jaw, intense stare',
      conflict: '',
    },
    {
      name: '惊讶', nameEn: 'Surprise',
      emoji: '😲',
      auCode: 'AU1+AU2+AU5+AU26',
      desc: '抬眉+睁眼+张嘴',
      descEn: 'Brow raisers + Upper lid raiser + Jaw drop',
      prompt: 'surprised, AU1+AU2+AU5+AU26, jaw dropped, wide eyes',
      conflict: '',
    },
    {
      name: '恐惧', nameEn: 'Fear',
      emoji: '😨',
      auCode: 'AU1+AU2+AU4+AU5+AU20+AU26',
      desc: '眉毛上挑拉平+张嘴，恐惧复合',
      descEn: 'Brow raisers + Lowerer + Lid raiser + Lip stretcher + Jaw drop',
      prompt: 'fear expression, AU1+AU2+AU4+AU5+AU20+AU26, wide eyes, tense',
      conflict: '',
    },
    {
      name: '厌恶', nameEn: 'Disgust',
      emoji: '🤢',
      auCode: 'AU9+AU15+AU16',
      desc: '鼻子皱起+嘴角下拉+嘴唇下压',
      descEn: 'Nose wrinkler + Lip corner depressor + Lower lip depressor',
      prompt: 'disgust face, AU9+AU15+AU16, nose wrinkle, upper lip raised',
      conflict: '',
    },
    {
      name: '轻蔑', nameEn: 'Contempt',
      emoji: '😏',
      auCode: 'AU12R+AU14R',
      desc: '单侧嘴角上扬，轻蔑特有表情',
      descEn: 'Unilateral lip corner puller, unique contempt marker',
      prompt: 'contempt expression, AU12R+AU14R, one-sided smirk, subtle',
      conflict: '',
    },
  ],

  compound: [
    {
      name: '惊喜', nameEn: 'Joyful Surprise',
      emoji: '🤩',
      auCode: 'AU1+AU2+AU6+AU12+AU26',
      desc: '惊讶+真笑复合表情',
      descEn: 'Surprise + Genuine smile compound',
      prompt: 'surprised happy, AU1+AU2+AU6+AU12+AU26, delighted shock',
      conflict: '',
    },
    {
      name: '悲愤', nameEn: 'Grief & Anger',
      emoji: '😤',
      auCode: 'AU1+AU4+AU15+AU23',
      desc: '悲伤+愤怒复合',
      descEn: 'Sadness + Anger compound',
      prompt: 'grief anger, AU1+AU4+AU15+AU23, frustrated tears',
      conflict: '',
    },
    {
      name: '苦笑', nameEn: 'Wry Smile',
      emoji: '😅',
      auCode: 'AU6+AU12+AU4',
      desc: '真笑叠加轻微皱眉，苦中带笑',
      descEn: 'Genuine smile with slight brow furrow, bittersweet',
      prompt: 'wry smile, bittersweet, AU6+AU12+AU4, rueful expression',
      conflict: '',
    },
    {
      name: '尴尬', nameEn: 'Awkward',
      emoji: '😳',
      auCode: 'AU12+AU20+AU4',
      desc: '社交性笑+嘴唇拉伸+皱眉',
      descEn: 'Social smile + Lip stretcher + Brow furrow, embarrassed',
      prompt: 'awkward expression, AU12+AU20+AU4, embarrassed, flushed',
      conflict: '',
    },
  ],

  micro: [
    {
      name: '愤怒泄露', nameEn: 'Anger Leak',
      emoji: '😡',
      auCode: 'AU4+AU5',
      desc: '1-3帧微表情，隐忍愤怒',
      descEn: '1-3 frame micro expression, suppressed anger flash',
      prompt: 'micro expression anger, AU4+AU5, suppressed, fleeting 1-3 frames',
      conflict: '',
    },
    {
      name: '恐惧掩饰', nameEn: 'Fear Mask',
      emoji: '😬',
      auCode: 'AU1+AU2+AU20',
      desc: '极短暂恐惧闪现，被笑容遮盖',
      descEn: 'Brief fear flash masked by smile, concealed micro expression',
      prompt: 'micro fear masked, AU1+AU2+AU20, fleeting, hidden anxiety',
      conflict: '',
    },
    {
      name: '真实满足', nameEn: 'Genuine Satisfaction',
      emoji: '😌',
      auCode: 'AU6',
      desc: '真实眼部收缩，眼轮匝肌激活（Duchenne 标记）',
      descEn: 'Orbicularis oculi activation, eye crinkle only, Duchenne marker',
      prompt: 'genuine satisfaction, Duchenne marker, AU6 only, subtle contentment',
      conflict: '',
    },
  ],

  single: [
    {
      name: '内侧眉上提', nameEn: 'Inner Brow Raise',
      emoji: '🤨',
      auCode: 'AU1',
      desc: '额肌内侧，额头中部皱纹',
      descEn: 'Frontalis medial, inner forehead wrinkles',
      prompt: 'AU1, inner brow raiser, concerned look, single AU',
      conflict: '与AU4部分拮抗',
    },
    {
      name: '外侧眉上提', nameEn: 'Outer Brow Raise',
      emoji: '🙄',
      auCode: 'AU2',
      desc: '额肌外侧，外眉弓抬高',
      descEn: 'Frontalis lateral, outer brow elevation',
      prompt: 'AU2, outer brow raiser, skeptical look, single AU',
      conflict: '',
    },
    {
      name: '皱眉', nameEn: 'Brow Lowerer',
      emoji: '🤔',
      auCode: 'AU4',
      desc: '皱眉肌，眉心挤压内聚',
      descEn: 'Corrugator supercilii, brow furrow, medial brow pull',
      prompt: 'AU4, brow lowerer, concentrate, thinking expression',
      conflict: '与AU1/AU2冲突',
    },
    {
      name: '上眼睑上提', nameEn: 'Upper Lid Raise',
      emoji: '😯',
      auCode: 'AU5',
      desc: '提睑肌，眼白暴露增加',
      descEn: 'Levator palpebrae, sclera exposure increase, wide eye',
      prompt: 'AU5, upper lid raiser, wide eyes, alert, single AU',
      conflict: '',
    },
    {
      name: '嘴角上扬', nameEn: 'Lip Corner Pull',
      emoji: '😊',
      auCode: 'AU12',
      desc: '颧大肌，嘴角斜向上提',
      descEn: 'Zygomaticus major, lip corner puller, smile basis',
      prompt: 'AU12, lip corner puller, smile, single AU',
      conflict: '',
    },
    {
      name: '嘴角下拉', nameEn: 'Lip Corner Depress',
      emoji: '🙁',
      auCode: 'AU15',
      desc: '降口角肌，嘴角下垂',
      descEn: 'Depressor anguli oris, lip corner depressor, sad mouth',
      prompt: 'AU15, lip corner depressor, sad mouth, single AU',
      conflict: '与AU12拮抗',
    },
  ],
}

export const CATEGORIES = [
  { name: '基础情绪', nameEn: 'Basic',    type: 'basic',    emoji: '😄', color: '#f97316' },
  { name: '复合表情', nameEn: 'Compound', type: 'compound', emoji: '🤩', color: '#8b5cf6' },
  { name: '微表情',   nameEn: 'Micro',    type: 'micro',    emoji: '😬', color: '#06b6d4' },
  { name: '单个AU',   nameEn: 'Single AU',type: 'single',   emoji: '🤔', color: '#10b981' },
]
