const RAW_AU_DATA = {
  "basic": [
    {
      "id": "basic_001",
      "nameCn": "真笑(自然)",
      "nameEn": "Genuine Smile",
      "category": "basic",
      "subCategory": "",
      "auCode": "AU6+AU12",
      "auFull": "AU6(眼轮匝肌)+AU12(颧大肌)",
      "strength": "3-4级",
      "muscle": "眼角收缩+嘴角上扬",
      "conflict": "",
      "descCn": "影视级真实笑容，眼部带皱纹，无表演感",
      "descEn": "Natural smile with eye wrinkles, authentic",
      "promptCn": "电影特写，真实自然笑容，眼角收缩，嘴角上扬，高清写实，面部无扭曲",
      "promptEn": "cinematic close-up, genuine smile, AU6+AU12, photorealistic, no facial distortion",
      "scene": "影视特写/日常剧情/数字人",
      "isMicro": false,
      "icon": "fa-regular fa-face-laugh-squint",
      "faceImg": "https://picsum.photos/200/200?woman=smile"
    },
    {
      "id": "basic_002",
      "nameCn": "假笑(职业)",
      "nameEn": "Fake Smile",
      "category": "basic",
      "subCategory": "",
      "auCode": "AU12",
      "auFull": "AU12(颧大肌)",
      "strength": "1-2级",
      "muscle": "仅颧大肌拉升，眼部无动作",
      "conflict": "",
      "descCn": "社交/职业假笑，无眼部参与，表情僵硬",
      "descEn": "Social/professional smile, no eye movement",
      "promptCn": "职业假笑，面部僵硬，仅嘴角上扬，适合商务场景",
      "promptEn": "professional fake smile, AU12, stiff facial expression",
      "scene": "职场社交/商务镜头/短视频",
      "isMicro": false,
      "icon": "fa-regular fa-face-smile",
      "faceImg": "https://picsum.photos/200/200?woman=fakesmile"
    },
    {
      "id": "basic_003",
      "nameCn": "悲伤",
      "nameEn": "Sadness",
      "category": "basic",
      "subCategory": "",
      "auCode": "AU1+AU4+AU15",
      "auFull": "AU1+AU4+AU15",
      "strength": "2-4级",
      "muscle": "眉头上提+皱眉+嘴角下拉",
      "conflict": "",
      "descCn": "难过、委屈、低落的基础悲伤表情",
      "descEn": "Basic sad, gloomy, wronged expression",
      "promptCn": "悲伤神情，眉头微蹙，嘴角下撇，眼眶微红，电影级柔光",
      "promptEn": "sad expression, AU1+AU4+AU15, teary eyes, soft cinematic lighting",
      "scene": "情感戏/哭戏铺垫/人物低落",
      "isMicro": false,
      "icon": "fa-regular fa-face-sad-tear",
      "faceImg": "https://picsum.photos/200/200?woman=sad"
    },
    {
      "id": "basic_004",
      "nameCn": "愤怒",
      "nameEn": "Anger",
      "category": "basic",
      "subCategory": "",
      "auCode": "AU4+AU5+AU23",
      "auFull": "AU4+AU5+AU23",
      "strength": "3-5级",
      "muscle": "皱眉+瞪眼+嘴唇紧绷",
      "conflict": "",
      "descCn": "愤怒、愠怒、克制的怒火表情",
      "descEn": "Angry, irritated, restrained fury",
      "promptCn": "愤怒特写，皱眉瞪眼，牙关紧咬，面部紧绷，强对比戏剧光",
      "promptEn": "angry face, AU4+AU5+AU23, clenched jaw, dramatic high-contrast light",
      "scene": "冲突戏/对峙镜头/反派表情",
      "isMicro": false,
      "icon": "fa-regular fa-face-angry",
      "faceImg": "https://picsum.photos/200/200?woman=angry"
    },
    {
      "id": "basic_005",
      "nameCn": "恐惧",
      "nameEn": "Fear",
      "category": "basic",
      "subCategory": "",
      "auCode": "AU1+AU2+AU5+AU20+AU26",
      "auFull": "AU1+AU2+AU5+AU20+AU26",
      "strength": "3-5级",
      "muscle": "抬眉+瞪眼+嘴唇横拉+下颌下垂",
      "conflict": "",
      "descCn": "惊恐、害怕、紧张的恐惧表情",
      "descEn": "Fear, panic, nervous expression",
      "promptCn": "惊恐神情，双眼瞪大，嘴唇拉伸，下颌微张，惊悚暗光氛围",
      "promptEn": "terrified face, AU1+AU2+AU5+AU20+AU26, horror low-key lighting",
      "scene": "惊悚片/危险场景/惊吓反应",
      "isMicro": false,
      "icon": "fa-regular fa-face-screaming",
      "faceImg": "https://picsum.photos/200/200?woman=scared"
    },
    {
      "id": "basic_006",
      "nameCn": "惊讶",
      "nameEn": "Surprise",
      "category": "basic",
      "subCategory": "",
      "auCode": "AU1+AU2+AU5+AU26",
      "auFull": "AU1+AU2+AU5+AU26",
      "strength": "2-3级",
      "muscle": "抬眉+瞪眼+下颌自然下垂",
      "conflict": "",
      "descCn": "短暂吃惊、意外的中性惊讶",
      "descEn": "Neutral surprise, short-term shock",
      "promptCn": "惊讶表情，抬眉睁眼，嘴巴微张，反应自然，电影写实",
      "promptEn": "surprised expression, AU1+AU2+AU5+AU26, natural reaction, photorealistic",
      "scene": "剧情反转/突发信息/日常反应",
      "isMicro": false,
      "icon": "fa-regular fa-face-surprise",
      "faceImg": "https://picsum.photos/200/200?woman=surprised"
    },
    {
      "id": "basic_007",
      "nameCn": "厌恶",
      "nameEn": "Disgust",
      "category": "basic",
      "subCategory": "",
      "auCode": "AU9+AU10",
      "auFull": "AU9+AU10",
      "strength": "2-4级",
      "muscle": "皱鼻+上唇提起",
      "conflict": "",
      "descCn": "嫌弃、反胃、鄙夷的厌恶表情",
      "descEn": "Disgusted, repulsive, disdainful",
      "promptCn": "厌恶神情，皱鼻撇嘴，上唇抬起，面部嫌弃感明显",
      "promptEn": "disgusted face, AU9+AU10, wrinkled nose, obvious disdain",
      "scene": "嫌弃镜头/反胃反应/负面剧情",
      "isMicro": false,
      "icon": "fa-regular fa-face-dizzy",
      "faceImg": "https://picsum.photos/200/200?woman=disgust"
    },
    {
      "id": "basic_008",
      "nameCn": "轻蔑",
      "nameEn": "Contempt",
      "category": "basic",
      "subCategory": "",
      "auCode": "单侧AU12+AU14",
      "auFull": "Unilateral AU12+AU14",
      "strength": "1-3级",
      "muscle": "单侧嘴角上扬+颊肌收紧",
      "conflict": "",
      "descCn": "不屑、高傲、嘲讽的单侧轻蔑",
      "descEn": "Unilateral contempt, arrogant, sarcastic",
      "promptCn": "轻蔑表情，单侧嘴角上扬，斜视，高傲神态，电影特写",
      "promptEn": "contemptuous, unilateral AU12+AU14, side glance, arrogant",
      "scene": "对峙戏/优越感/反派神态",
      "isMicro": false,
      "icon": "fa-regular fa-face-meh-blank",
      "faceImg": "https://picsum.photos/200/200?woman=contempt"
    }
  ],
  "compound": [
    {
      "id": "compound_001",
      "nameCn": "惊喜",
      "nameEn": "Surprised Happy",
      "category": "compound",
      "subCategory": "正向情绪复合",
      "auCode": "AU1+AU2+AU6+AU12+AU26",
      "auFull": "AU1+AU2+AU6+AU12+AU26",
      "strength": "3-4级",
      "muscle": "抬眉+真笑+下颌微张",
      "conflict": "",
      "descCn": "惊讶叠加开心，影视高光表情",
      "descEn": "Surprise + happy compound expression",
      "promptCn": "惊喜神情，抬眉微笑，眼部自然收缩，张嘴，温暖电影光",
      "promptEn": "surprised happy, AU1+AU2+AU6+AU12+AU26, warm cinematic light",
      "scene": "重逢/惊喜礼物/剧情正向反转",
      "isMicro": false,
      "icon": "fa-regular fa-face-laugh-beam",
      "faceImg": "https://picsum.photos/200/200?woman=surprisedhappy"
    },
    {
      "id": "compound_002",
      "nameCn": "悲愤",
      "nameEn": "Grief & Anger",
      "category": "compound",
      "subCategory": "负向情绪复合",
      "auCode": "AU1+AU4+AU15+AU23",
      "auFull": "AU1+AU4+AU15+AU23",
      "strength": "3-5级",
      "muscle": "悲伤+愤怒肌肉叠加",
      "conflict": "",
      "descCn": "悲伤与愤怒交织，痛苦悲愤",
      "descEn": "Grief mixed with anger, painful",
      "promptCn": "悲愤表情，悲伤皱眉，嘴角下撇，嘴唇紧绷，强情绪特写",
      "promptEn": "grief and anger, AU1+AU4+AU15+AU23, strong emotional close-up",
      "scene": "悲剧戏/背叛剧情/强情感冲突",
      "isMicro": false,
      "icon": "fa-regular fa-face-sad-angry",
      "faceImg": "https://picsum.photos/200/200?woman=grief"
    },
    {
      "id": "compound_003",
      "nameCn": "悲恐",
      "nameEn": "Sad & Scared",
      "category": "compound",
      "subCategory": "负向情绪复合",
      "auCode": "AU1+AU2+AU4+AU15+AU20",
      "auFull": "AU1+AU2+AU4+AU15+AU20",
      "strength": "3-4级",
      "muscle": "悲伤+恐惧肌肉叠加",
      "conflict": "",
      "descCn": "悲伤叠加恐惧，无助绝望",
      "descEn": "Sadness mixed with fear, helpless",
      "promptCn": "悲恐神情，含泪瞪眼，嘴角下撇，面部紧绷，压抑情绪",
      "promptEn": "sad and scared, AU1+AU2+AU4+AU15+AU20, depressed emotion",
      "scene": "绝境场景/生离死别/悬疑悲剧",
      "isMicro": false,
      "icon": "fa-regular fa-face-sad-cry",
      "faceImg": "https://picsum.photos/200/200?woman=sadscared"
    },
    {
      "id": "compound_004",
      "nameCn": "忍笑",
      "nameEn": "Suppressed Smile",
      "category": "compound",
      "subCategory": "矛盾戏剧化复合",
      "auCode": "AU6+AU12+AU23",
      "auFull": "AU6+AU12+AU23",
      "strength": "1-2级",
      "muscle": "真笑+嘴唇压紧克制",
      "conflict": "",
      "descCn": "强忍笑意，憋笑的细腻表情",
      "descEn": "Suppressed smile, holding back laughter",
      "promptCn": "忍笑表情，眼部微笑，嘴角上扬，嘴唇紧绷克制，自然写实",
      "promptEn": "suppressed smile, AU6+AU12+AU23, natural photorealistic",
      "scene": "喜剧憋笑/尴尬场合/含蓄情绪",
      "isMicro": false,
      "icon": "fa-regular fa-face-grin-squint",
      "faceImg": "https://picsum.photos/200/200?woman=suppresssmile"
    },
    {
      "id": "compound_005",
      "nameCn": "强颜欢笑",
      "nameEn": "Forced Smile",
      "category": "compound",
      "subCategory": "矛盾戏剧化复合",
      "auCode": "AU12+AU1+AU15",
      "auFull": "AU12+AU1+AU15",
      "strength": "1-2级",
      "muscle": "假笑叠加悲伤肌肉",
      "conflict": "",
      "descCn": "表面微笑内心难过，成年人隐忍",
      "descEn": "Forced smile with inner sadness",
      "promptCn": "强颜欢笑，嘴角上扬但眉眼悲伤，表情克制，电影特写",
      "promptEn": "forced smile, AU12+AU1+AU15, restrained expression, close-up",
      "scene": "离别场景/隐忍情绪/现实向剧情",
      "isMicro": false,
      "icon": "fa-regular fa-face-smile-wink",
      "faceImg": "https://picsum.photos/200/200?woman=forcedsmile"
    },
    {
      "id": "compound_006",
      "nameCn": "尴尬",
      "nameEn": "Embarrassed",
      "category": "compound",
      "subCategory": "社交微表情复合",
      "auCode": "AU12+AU14+AU23",
      "auFull": "AU12+AU14+AU23",
      "strength": "1-2级",
      "muscle": "单侧微笑+嘴唇紧绷",
      "conflict": "",
      "descCn": "社交尴尬、不好意思的表情",
      "descEn": "Social embarrassment, awkward",
      "promptCn": "尴尬表情，单侧微笑，嘴唇微抿，眼神躲闪，自然写实",
      "promptEn": "embarrassed, AU12+AU14+AU23, awkward expression",
      "scene": "社交失误/冷场/不好意思",
      "isMicro": false,
      "icon": "fa-regular fa-face-grin",
      "faceImg": "https://picsum.photos/200/200?woman=embarrassed"
    }
  ],
  "micro": [
    {
      "id": "micro_001",
      "nameCn": "愤怒泄露",
      "nameEn": "Anger Leakage",
      "category": "micro",
      "subCategory": "",
      "auCode": "AU4+AU5",
      "auFull": "AU4+AU5",
      "strength": "1-2级",
      "muscle": "轻微皱眉+微瞪眼",
      "conflict": "",
      "descCn": "1-3帧微表情，隐藏愤怒外泄",
      "descEn": "1-3 frame microexpression, hidden anger",
      "promptCn": "微表情愤怒泄露，快速皱眉瞪眼，特写，情绪一闪而过",
      "promptEn": "microexpression anger leakage, AU4+AU5, quick close-up flash",
      "scene": "悬疑戏/内心隐忍/微表情分析",
      "isMicro": true,
      "icon": "fa-solid fa-eye",
      "faceImg": "https://picsum.photos/200/200?woman=microangry"
    },
    {
      "id": "micro_002",
      "nameCn": "悲伤泄露",
      "nameEn": "Sad Leakage",
      "category": "micro",
      "subCategory": "",
      "auCode": "AU1+AU15",
      "auFull": "AU1+AU15",
      "strength": "1级",
      "muscle": "轻微抬眉+嘴角微下拉",
      "conflict": "",
      "descCn": "1-3帧微表情，强忍悲伤",
      "descEn": "1-3 frame microexpression, hidden sadness",
      "promptCn": "微表情悲伤泄露，眉眼微垂，快速闪过，硬汉隐忍特写",
      "promptEn": "microexpression sad leakage, AU1+AU15, tough guy restrained",
      "scene": "硬汉哭戏/强装坚强/内心难过",
      "isMicro": true,
      "icon": "fa-solid fa-eye-low-vision",
      "faceImg": "https://picsum.photos/200/200?woman=microsad"
    },
    {
      "id": "micro_003",
      "nameCn": "厌恶泄露",
      "nameEn": "Disgust Leakage",
      "category": "micro",
      "subCategory": "",
      "auCode": "AU9+AU10",
      "auFull": "AU9+AU10",
      "strength": "1级",
      "muscle": "轻微皱鼻+上唇微提",
      "conflict": "",
      "descCn": "1-3帧微表情，隐性嫌弃",
      "descEn": "1-3 frame microexpression, hidden disgust",
      "promptCn": "微表情厌恶泄露，轻皱鼻子，表情一闪而过，社交场景",
      "promptEn": "microexpression disgust leakage, AU9+AU10, social scene flash",
      "scene": "职场客套/隐性嫌弃/社交伪装",
      "isMicro": true,
      "icon": "fa-solid fa-eye",
      "faceImg": "https://picsum.photos/200/200?woman=microdisgust"
    },
    {
      "id": "micro_004",
      "nameCn": "喜悦泄露",
      "nameEn": "Happy Leakage",
      "category": "micro",
      "subCategory": "",
      "auCode": "AU6+AU12",
      "auFull": "AU6+AU12",
      "strength": "1级",
      "muscle": "轻微真笑肌肉动作",
      "conflict": "",
      "descCn": "1-3帧微表情，暗喜偷笑",
      "descEn": "1-3 frame microexpression, hidden joy",
      "promptCn": "微表情喜悦泄露，轻微微笑，眼部微动，窃喜特写",
      "promptEn": "microexpression happy leakage, AU6+AU12, quiet joy close-up",
      "scene": "计谋得逞/暗喜/内敛开心",
      "isMicro": true,
      "icon": "fa-solid fa-eye",
      "faceImg": "https://picsum.photos/200/200?woman=microhappy"
    }
  ],
  "single": [
    {
      "id": "single_001",
      "nameCn": "内侧眉上提",
      "nameEn": "Inner Brow Raiser",
      "category": "single",
      "subCategory": "上半脸核心动作单元",
      "auCode": "AU1",
      "auFull": "AU1(额肌内侧)",
      "strength": "1-5级",
      "muscle": "额肌内侧收缩，眉头上抬",
      "conflict": "与AU4冲突",
      "descCn": "悲伤、恳求、恐惧的核心单AU",
      "descEn": "Core AU for sadness, beg, fear",
      "promptCn": "内侧眉头上提，额头中部细纹，悲伤神态",
      "promptEn": "AU1, inner brow raiser, middle forehead lines",
      "scene": "自定义表情/悲伤组合/哭戏",
      "isMicro": false,
      "icon": "fa-solid fa-eyebrow",
      "faceImg": "https://picsum.photos/200/200?woman=au1"
    },
    {
      "id": "single_002",
      "nameCn": "外侧眉上提",
      "nameEn": "Outer Brow Raiser",
      "category": "single",
      "subCategory": "上半脸核心动作单元",
      "auCode": "AU2",
      "auFull": "AU2(额肌外侧)",
      "strength": "1-5级",
      "muscle": "额肌外侧收缩，眉尾上抬",
      "conflict": "与AU4冲突",
      "descCn": "惊讶、怀疑、挑衅的核心单AU",
      "descEn": "Core AU for surprise, doubt, provocation",
      "promptCn": "外侧眉头上抬，眉峰抬高，惊讶神态",
      "promptEn": "AU2, outer brow raiser, raised brow peak",
      "scene": "自定义表情/惊讶组合/怀疑神态",
      "isMicro": false,
      "icon": "fa-solid fa-eyebrow",
      "faceImg": "https://picsum.photos/200/200?woman=au2"
    },
    {
      "id": "single_003",
      "nameCn": "皱眉",
      "nameEn": "Brow Lowerer",
      "category": "single",
      "subCategory": "上半脸核心动作单元",
      "auCode": "AU4",
      "auFull": "AU4(皱眉肌)",
      "strength": "1-5级",
      "muscle": "皱眉肌收缩，眉心挤压",
      "conflict": "与AU1/AU2冲突",
      "descCn": "愤怒、专注、痛苦的核心单AU",
      "descEn": "Core AU for anger, focus, pain",
      "promptCn": "眉心挤压皱眉，严肃愤怒神态，面部紧绷",
      "promptEn": "AU4, brow lowerer, frowning, serious expression",
      "scene": "自定义表情/愤怒组合/专注神态",
      "isMicro": false,
      "icon": "fa-solid fa-eyebrow",
      "faceImg": "https://picsum.photos/200/200?woman=au4"
    },
    {
      "id": "single_004",
      "nameCn": "上眼睑提升",
      "nameEn": "Upper Lid Raiser",
      "category": "single",
      "subCategory": "上半脸核心动作单元",
      "auCode": "AU5",
      "auFull": "AU5(上睑提肌)",
      "strength": "1-5级",
      "muscle": "上睑提肌收缩，眼球暴露增加",
      "conflict": "",
      "descCn": "愤怒、恐惧、惊讶的单AU",
      "descEn": "Core AU for anger, fear, surprise",
      "promptCn": "上眼睑提升，眼球暴露更多，震慑神态",
      "promptEn": "AU5, upper lid raiser, more eyeball exposure",
      "scene": "自定义表情/愤怒恐惧组合",
      "isMicro": false,
      "icon": "fa-solid fa-eye",
      "faceImg": "https://picsum.photos/200/200?woman=au5"
    },
    {
      "id": "single_005",
      "nameCn": "脸颊提升",
      "nameEn": "Cheek Raiser",
      "category": "single",
      "subCategory": "中脸核心动作单元",
      "auCode": "AU6",
      "auFull": "AU6(眼轮匝肌)",
      "strength": "1-5级",
      "muscle": "眼轮匝肌收缩，脸颊上抬",
      "conflict": "",
      "descCn": "真笑标志性单AU，区分真假笑",
      "descEn": "Key AU for genuine smile",
      "promptCn": "脸颊提升，眼角细纹，真实微笑眼部动作",
      "promptEn": "AU6, cheek raiser, eye wrinkles, real smile",
      "scene": "自定义笑容/真笑组合/温柔表情",
      "isMicro": false,
      "icon": "fa-solid fa-face-smile",
      "faceImg": "https://picsum.photos/200/200?woman=au6"
    },
    {
      "id": "single_006",
      "nameCn": "嘴角上扬",
      "nameEn": "Lip Corner Puller",
      "category": "single",
      "subCategory": "下半脸核心动作单元",
      "auCode": "AU12",
      "auFull": "AU12(颧大肌)",
      "strength": "1-5级",
      "muscle": "颧大肌收缩，嘴角斜上抬",
      "conflict": "与AU15冲突",
      "descCn": "微笑核心单AU，所有笑容基础",
      "descEn": "Basic AU for all smiles",
      "promptCn": "嘴角斜向上抬，微笑基础动作，自然神态",
      "promptEn": "AU12, lip corner puller, basic smile action",
      "scene": "自定义笑容/所有微笑类表情",
      "isMicro": false,
      "icon": "fa-solid fa-mouth",
      "faceImg": "https://picsum.photos/200/200?woman=au12"
    },
    {
      "id": "single_007",
      "nameCn": "嘴角下拉",
      "nameEn": "Lip Corner Depressor",
      "category": "single",
      "subCategory": "下半脸核心动作单元",
      "auCode": "AU15",
      "auFull": "AU15(降口角肌)",
      "strength": "1-5级",
      "muscle": "降口角肌收缩，嘴角下压",
      "conflict": "与AU12冲突",
      "descCn": "悲伤、难过、不屑的单AU",
      "descEn": "Core AU for sadness, disdain",
      "promptCn": "嘴角向下压，悲伤低落神态，面部下垮",
      "promptEn": "AU15, lip corner depressor, sad gloomy expression",
      "scene": "自定义悲伤/不屑组合/难过表情",
      "isMicro": false,
      "icon": "fa-solid fa-mouth",
      "faceImg": "https://picsum.photos/200/200?woman=au15"
    },
    {
      "id": "single_008",
      "nameCn": "下巴上抬",
      "nameEn": "Chin Raiser",
      "category": "single",
      "subCategory": "下半脸核心动作单元",
      "auCode": "AU17",
      "auFull": "AU17(颏肌)",
      "strength": "1-4级",
      "muscle": "颏肌收缩，下巴顶起下唇",
      "conflict": "",
      "descCn": "委屈、强忍泪水、生气的单AU",
      "descEn": "Core AU for grievance, holding tears",
      "promptCn": "下巴上抬，顶起下唇，委屈强忍神态",
      "promptEn": "AU17, chin raiser, grievance holding tears",
      "scene": "自定义委屈/哭戏/生气表情",
      "isMicro": false,
      "icon": "fa-solid fa-face-frown",
      "faceImg": "https://picsum.photos/200/200?woman=au17"
    }
  ],
  "lipSync": [
    {
      "id": "lipsync_001",
      "nameCn": "a (啊)",
      "nameEn": "a (ah)",
      "category": "lipSync",
      "subCategory": "中文普通话发音",
      "auCode": "AU26+AU27",
      "auFull": "AU26+AU27",
      "strength": "3-4级",
      "muscle": "下颌下垂+嘴唇张开",
      "conflict": "",
      "descCn": "中文拼音a的口型，开口较大",
      "descEn": "Chinese pinyin 'a' mouth shape",
      "promptCn": "中文a发音口型，嘴巴张开，下颌下垂，自然说话状态",
      "promptEn": "Chinese 'a' pronunciation, mouth open, jaw dropped",
      "scene": "中文口型/语音驱动",
      "isMicro": false,
      "icon": "fa-solid fa-microphone",
      "faceImg": "https://picsum.photos/200/200?woman=a",
      "pinyin": "a",
      "pronunciation": "开口较大，舌位低平"
    },
    {
      "id": "lipsync_002",
      "nameCn": "o (喔)",
      "nameEn": "o (oh)",
      "category": "lipSync",
      "subCategory": "中文普通话发音",
      "auCode": "AU18+AU26",
      "auFull": "AU18+AU26",
      "strength": "2-3级",
      "muscle": "嘴唇前突+下颌微张",
      "conflict": "",
      "descCn": "中文拼音o的口型，嘴唇前突",
      "descEn": "Chinese pinyin 'o' mouth shape",
      "promptCn": "中文o发音口型，嘴唇前突成圆形，下颌微张",
      "promptEn": "Chinese 'o' pronunciation, lips rounded, jaw slightly open",
      "scene": "中文口型/语音驱动",
      "isMicro": false,
      "icon": "fa-solid fa-microphone",
      "faceImg": "https://picsum.photos/200/200?woman=o",
      "pinyin": "o",
      "pronunciation": "嘴唇前突成圆形，舌位半高"
    },
    {
      "id": "lipsync_003",
      "nameCn": "e (呃)",
      "nameEn": "e (uh)",
      "category": "lipSync",
      "subCategory": "中文普通话发音",
      "auCode": "AU26+AU27",
      "auFull": "AU26+AU27",
      "strength": "2-3级",
      "muscle": "下颌微张+嘴角微拉",
      "conflict": "",
      "descCn": "中文拼音e的口型，嘴角微拉",
      "descEn": "Chinese pinyin 'e' mouth shape",
      "promptCn": "中文e发音口型，嘴巴微张，嘴角向两侧微拉",
      "promptEn": "Chinese 'e' pronunciation, mouth slightly open, lips stretched",
      "scene": "中文口型/语音驱动",
      "isMicro": false,
      "icon": "fa-solid fa-microphone",
      "faceImg": "https://picsum.photos/200/200?woman=e",
      "pinyin": "e",
      "pronunciation": "嘴角微拉，舌位靠后"
    },
    {
      "id": "lipsync_004",
      "nameCn": "i (一)",
      "nameEn": "i (ee)",
      "category": "lipSync",
      "subCategory": "中文普通话发音",
      "auCode": "AU12+AU20",
      "auFull": "AU12+AU20",
      "strength": "1-2级",
      "muscle": "嘴角上扬+嘴唇横拉",
      "conflict": "",
      "descCn": "中文拼音i的口型，嘴角上扬",
      "descEn": "Chinese pinyin 'i' mouth shape",
      "promptCn": "中文i发音口型，嘴角上扬，嘴唇横向拉伸",
      "promptEn": "Chinese 'i' pronunciation, lips stretched, corners up",
      "scene": "中文口型/语音驱动",
      "isMicro": false,
      "icon": "fa-solid fa-microphone",
      "faceImg": "https://picsum.photos/200/200?woman=i",
      "pinyin": "i",
      "pronunciation": "嘴角上扬，嘴唇横向拉伸，舌位高"
    },
    {
      "id": "lipsync_005",
      "nameCn": "u (乌)",
      "nameEn": "u (oo)",
      "category": "lipSync",
      "subCategory": "中文普通话发音",
      "auCode": "AU18",
      "auFull": "AU18",
      "strength": "2-3级",
      "muscle": "嘴唇前突成圆形",
      "conflict": "",
      "descCn": "中文拼音u的口型，嘴唇前突",
      "descEn": "Chinese pinyin 'u' mouth shape",
      "promptCn": "中文u发音口型，嘴唇前突成圆形，收紧",
      "promptEn": "Chinese 'u' pronunciation, lips rounded and protruded",
      "scene": "中文口型/语音驱动",
      "isMicro": false,
      "icon": "fa-solid fa-microphone",
      "faceImg": "https://picsum.photos/200/200?woman=u",
      "pinyin": "u",
      "pronunciation": "嘴唇前突成圆形，收紧，舌位高"
    }
  ]
}

const CATEGORY_META = {
  basic:    { name: '基础情绪', nameEn: 'Basic Emotions', emoji: '😄', color: '#f97316', icon: '🎭' },
  compound: { name: '复合表情', nameEn: 'Compound Expressions', emoji: '🤩', color: '#8b5cf6', icon: '🎨' },
  micro:    { name: '微表情',   nameEn: 'Micro Expressions', emoji: '😬', color: '#06b6d4', icon: '⚡' },
  single:   { name: '单个AU',   nameEn: 'Single AUs', emoji: '🤔', color: '#10b981', icon: '🔬' },
  lipSync:  { name: '口型同步', nameEn: 'Lip Sync', emoji: '🗣️', color: '#0ea5e9', icon: '🎤' },
}

const ITEM_FALLBACK_EMOJI = {
  basic: '🙂',
  compound: '🧩',
  micro: '⚡',
  single: '🔹',
  lipSync: '🗣️',
}

function normalizeItem(item) {
  const emoji = item.emoji || ITEM_FALLBACK_EMOJI[item.category] || '🙂'
  return {
    ...item,
    emoji,
    name: item.nameCn,
    desc: item.descCn,
    prompt: item.promptCn,
  }
}

export const AU_DATA = Object.fromEntries(
  Object.entries(RAW_AU_DATA).map(([key, list]) => [key, list.map(normalizeItem)])
)

export const CATEGORIES = Object.entries(CATEGORY_META).map(([type, meta]) => ({
  type,
  ...meta,
  desc: `${meta.name} 分类`,
  descEn: `${meta.nameEn} category`,
}))
